development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 895395861269-7q0lsscdak4322cbqof6v7amu8h7cgec.apps.googleusercontent.com
  google_client_secret: m5_XYUmB7QMbbhhNQPNclrh7
